### ISSUE TITLE
Purple comments hard to read for someone with Protanopia

### ISSUE THREAD

**Issue by viktorzou** [DesiQuintans/Pebble-safe#1]
So I have Protanopia and searched for some RStudio Themes, but tbh the purple is really hard to read..
The other colors are great

**Comment by DesiQuintans** [comment]
Hi, you're right, I can see that from a simulation now. Must it be a dark theme, or can you use https://github.com/DesiQuintans/epergoes?

**Comment by viktorzou** [comment]
@DesiQuintans haha, sorry my comment sounded a bit harsh, I really dig your theme otherwise, I don't like epergoes that much. For now, i will stay with Pebble-safe. I think the purple just would need to be a bit more flat. I really like, that many people try to account for us people with color-difficulties. Also, the work of https://github.com/dtm2451/dittoSeq is really great, I think they perfected color and contrast optimization, if you want some inspiration.

**Comment by DesiQuintans** [comment]
Cheers, I'll keep this request in mind for future themes.
